export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const PARTICIPANTS_ERROR = 'PARTICIPANTS_ERROR';
export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const SET_LOADING = 'SET_LOADING';
export const GET_WINNER = 'GET_WINNER';
export const WINNERS_ERROR = 'WINNERS_ERROR';
